"""add requirements_fingerprint to jobs

Revision ID: 159392b23dd0
Revises: 6a494a138df0
Create Date: 2026-09-16 09:40:06.390873

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '159392b23dd0'
down_revision: str | Sequence[str] | None = '6a494a138df0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requirements_fingerprint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'requirements_fingerprint')
    # ### end Alembic commands ###
