"""add target_level to profiles

Revision ID: 1af87e230f79
Revises: 35cbc25fd32c
Create Date: 2026-09-16 18:29:04.600340

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1af87e230f79'
down_revision: str | Sequence[str] | None = '35cbc25fd32c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Added nullable, backfilled, then constrained — a direct NOT NULL add fails
    # against existing rows. Seeding from years_experience is only a starting
    # guess; target_level is about what someone wants next, not what they have.
    # add_column does not create the enum type the way create_table does, so it
    # has to be created explicitly before a column can reference it.
    target_level = sa.Enum(
        'intern', 'new_grad', 'junior', 'mid', 'senior', name='target_level'
    )
    target_level.create(op.get_bind(), checkfirst=True)
    op.add_column('profiles', sa.Column('target_level', target_level, nullable=True))
    op.execute(
        """
        UPDATE profiles SET target_level = CASE
            WHEN years_experience < 1 THEN 'new_grad'
            WHEN years_experience < 3 THEN 'junior'
            WHEN years_experience < 7 THEN 'mid'
            ELSE 'senior'
        END::target_level
        WHERE target_level IS NULL
        """
    )
    op.alter_column('profiles', 'target_level', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'target_level')
    # ### end Alembic commands ###
