"""add candidate application fields to profiles

Revision ID: 2e37b671bb82
Revises: 176176552348
Create Date: 2026-09-19 00:15:52.994953

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e37b671bb82'
down_revision: str | Sequence[str] | None = '176176552348'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('notice_period', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('current_ctc', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('expected_ctc', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('preferred_locations', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('work_authorization', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('has_offer_in_hand', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'has_offer_in_hand')
    op.drop_column('profiles', 'portfolio_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'work_authorization')
    op.drop_column('profiles', 'preferred_locations')
    op.drop_column('profiles', 'expected_ctc')
    op.drop_column('profiles', 'current_ctc')
    op.drop_column('profiles', 'notice_period')
    # ### end Alembic commands ###
