"""add ats_boards table

Revision ID: 35cbc25fd32c
Revises: 6b356561a093
Create Date: 2026-09-16 17:12:40.219637

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '35cbc25fd32c'
down_revision: str | Sequence[str] | None = '6b356561a093'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('verified_name', sa.String(), nullable=True),
    sa.Column('discovered_via', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'slug', name='uq_ats_boards_source_slug')
    )
    # Carry over the two companies that were hardcoded in app/workers/tasks, so
    # discovery keeps working the moment the poller starts reading this table.
    op.execute(
        "INSERT INTO ats_boards (source, slug, company_name, verified_name, discovered_via) "
        "VALUES ('greenhouse', 'stripe', 'Stripe', 'Stripe', 'seed'), "
        "('lever', 'palantir', 'Palantir', 'Palantir', 'seed')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ats_boards')
    # ### end Alembic commands ###
