"""add fill attempts

Revision ID: 575c3fd86903
Revises: 58d38c78c921
Create Date: 2026-09-22 22:38:06.204846

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '575c3fd86903'
down_revision: str | Sequence[str] | None = '58d38c78c921'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fill_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('filled', 'captcha_required', 'form_not_found', name='fill_attempt_status'), nullable=False),
    sa.Column('filled_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skipped_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('screenshot', sa.LargeBinary(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fill_attempts_application_id'), 'fill_attempts', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_fill_attempts_application_id'), table_name='fill_attempts')
    op.drop_table('fill_attempts')
    # Dropping the table leaves the enum type behind, and the next upgrade then
    # fails on CREATE TYPE with DuplicateObjectError — confirmed by running
    # down and up again against a real database, not assumed. Autogenerate does
    # not write this line.
    sa.Enum(name='fill_attempt_status').drop(op.get_bind())
