"""add draft answer fingerprint

Revision ID: 58d38c78c921
Revises: c46467c6f709
Create Date: 2026-09-21 19:20:33.816229

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '58d38c78c921'
down_revision: str | Sequence[str] | None = 'c46467c6f709'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('draft_answers', sa.Column('fingerprint', sa.String(), nullable=True))
    # Every row that exists right now was generated, not hand-written, so it has
    # to be marked stale rather than left NULL — NULL means "a person wrote
    # this, never regenerate it", and inheriting that would preserve exactly the
    # pre-fix answers this column exists to replace. The sentinel matches no
    # real fingerprint, so each one regenerates the next time it is asked for.
    op.execute("UPDATE draft_answers SET fingerprint = 'legacy' WHERE fingerprint IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_answers', 'fingerprint')
    # ### end Alembic commands ###
