"""add applications table

Revision ID: 5ee44d8cca8c
Revises: f1cf71ecc541
Create Date: 2026-09-15 16:21:57.246817

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ee44d8cca8c'
down_revision: str | Sequence[str] | None = 'f1cf71ecc541'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('interested', 'tailoring', 'ready_for_review', 'pending_captcha', 'approved', 'rejected_by_user', 'submitted', 'response_tracked', name='application_state'), nullable=False),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('resume_variant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['resume_variant_id'], ['resume_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'job_id', name='uq_applications_profile_job')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
