"""add pdf_bytes to resume_variants

Revision ID: 6a494a138df0
Revises: f0db0958a368
Create Date: 2026-09-15 23:21:14.158547

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a494a138df0'
down_revision: str | Sequence[str] | None = 'f0db0958a368'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_variants', sa.Column('pdf_bytes', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_variants', 'pdf_bytes')
    # ### end Alembic commands ###
