"""add job liveness tracking

Revision ID: 6b356561a093
Revises: 159392b23dd0
Create Date: 2026-09-16 11:11:30.006731

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b356561a093'
down_revision: str | Sequence[str] | None = '159392b23dd0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('jobs', sa.Column('missed_sweeps', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # The server_default stamps every existing row with now(), which would claim we
    # just saw jobs we may not have seen in weeks. Discovery is the last moment we
    # actually know they were listed.
    op.execute("UPDATE jobs SET last_seen_at = discovered_at")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'closed_at')
    op.drop_column('jobs', 'missed_sweeps')
    op.drop_column('jobs', 'last_seen_at')
    # ### end Alembic commands ###
