"""add unique constraint on jobs source and external_id

Revision ID: 6e1a79ece9ce
Revises: 151a1699d463
Create Date: 2026-09-04 17:31:35.031417

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e1a79ece9ce'
down_revision: str | Sequence[str] | None = '151a1699d463'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_jobs_source_external_id', 'jobs', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_source_external_id', 'jobs', type_='unique')
    # ### end Alembic commands ###
