"""add email phone location to profiles

Revision ID: f0db0958a368
Revises: 5ee44d8cca8c
Create Date: 2026-09-15 20:44:33.780251

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f0db0958a368'
down_revision: str | Sequence[str] | None = '5ee44d8cca8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # email added nullable first, backfilled, then constrained NOT NULL — a direct
    # NOT NULL add fails against any existing row (autogenerate doesn't know that).
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.execute("UPDATE profiles SET email = 'unknown+' || id || '@example.invalid' WHERE email IS NULL")
    op.alter_column('profiles', 'email', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
