"""add resume_variants table

Revision ID: f1cf71ecc541
Revises: fc02573fe837
Create Date: 2026-09-14 19:06:50.719053

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1cf71ecc541'
down_revision: str | Sequence[str] | None = 'fc02573fe837'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('role_label', sa.String(), nullable=False),
    sa.Column('emphasis_note', sa.String(), nullable=True),
    sa.Column('generated_content', sa.String(), nullable=False),
    sa.Column('unverified_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'role_label', name='uq_resume_variants_profile_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_variants')
    # ### end Alembic commands ###
