"""add years_experience to profiles

Revision ID: f758cc3513ad
Revises: 1db043d2a699
Create Date: 2026-09-09 18:48:56.536390

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f758cc3513ad'
down_revision: str | Sequence[str] | None = '1db043d2a699'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('years_experience', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'years_experience')
    # ### end Alembic commands ###
